### ISSUE TITLE
Training Sparsifier and Controller network

### ISSUE THREAD

**Issue by Jbwasse2** [xymeng/rmp_nav#2]
What are the steps needed in order to train the models given to us? It looks like training the controller requires the use of a file called "model_spec.yaml" that isn't located in this repo.

**Comment by xymeng** [comment]
I've updated the repo to include missing files. Please let me know if you can train the model.

**Comment by Jbwasse2** [comment]
I think I am getting an error with the visdom server, I have attached the corresponding log file. [log.txt](https://github.com/xymeng/rmp_nav/files/4932569/log.txt)
![err](https://user-images.githubusercontent.com/17070462/87692700-a43d9880-c751-11ea-9564-bdb77d23091b.png)



I have tried changing 
```
python launch_sim_server_load_balancer_multi.py gibson_12envs_gpu01_128.yaml 5000
```
to 
```
python launch_sim_server_load_balancer_multi.py gibson_12envs_gpu01_128.yaml 5001
```
to match the port in args.py, but instead I get the following and it hangs
![hang](https://user-images.githubusercontent.com/17070462/87693389-84f33b00-c752-11ea-8c95-a28a6f0328b9.png)

 Any thoughts?

**Comment by xymeng** [comment]
Oh I forgot to mention that you need to launch the visdom server before training:
`visdom -port=5001`

The port for launching the simulators is 5000. Please don't change that.

**Comment by Jbwasse2** [comment]
Sorry for the tardiness in my response, the CoRL deadline backed everything up for me. I retried running the code and am now getting this.

![update](https://user-images.githubusercontent.com/17070462/88701725-08584900-d0d0-11ea-8f60-122db49c9691.png)

**Comment by xymeng** [comment]
It's due to the change of implementation in PyTorch's sampler. I've updated the code.

**Comment by Jbwasse2** [comment]
Thanks! It looks like the controller is training.

**Comment by Jbwasse2** [comment]
For building the topological map in real life I think you forgot to push "../nav_graphs/cse2roboticslab/graph_config.yaml"

**Comment by xymeng** [comment]
My bad. I've added the missing file.

**Comment by Jbwasse2** [comment]
Thanks for your help! I really appreciate it. The graphics/code is great! I will let you know about the progress on getting this on my lab's robot once I get the results.
